name: DomChat
main: com.sarinsa.domchat.core.DomChat
version: 1.0.0-b
description: "A tiny chat utility plugin for Mr Dom; the man with the plan"
author: Sarinsa
depend: [Towny, EssentialsX, LuckPerms]
api-version: 1.13

commands:
  domchat:
    permission-message: You don't have permission to perform this command.
    permission: op
    description: Base command for the DomChat plugin.
    aliases:
      - domc